export const UPDATE_SERVICEDEFINITIONVO = 'UPDATE_SERVICEDEFINITIONVO';
export const UPDATE_SERVICEINSTANCEVO = 'UPDATE_SERVICEINSTANCEVO';
export const SET_SERVICEDEFINITION_TABLELOADING = 'SET_SERVICEDEFINITION_TABLELOADING';
export const SET_SERVICEINSTANCE_TABLELOADING = 'SET_SERVICEINSTANCE_TABLELOADING';
export const SET_SERVICEDISTRIBUTIONTHREADSTATE = 'SET_SERVICEDISTRIBUTIONTHREADSTATE';
